const data = {
  filter:{
    b1 : "팔리", b2: "오베아", b3:"스톡", b4: "리들리", b5 : "파소니",
    b6: "피나렐로", b7: "큐브", b8 : "룩", b9 : "비앙키", b10 : "구스토",
    b11: "타임", b12: "캐논데일", b13: "챕터2" , b14: "타임", b15: "비엠씨",
    b16 : "써벨로", b17: "포커스", b18: "세파스", b19: "라피에르", b20: "메리다",
    b21: "콜나고", b22: "예거", b23: "팩터", b24: "윌리어", b25: "엘파마", b26: "치폴리니",
    b41: "인세인",

    t1: "로드", t2: "사이클로크로스" , t3 : "그래블", t4 : "타임트라이얼",

    g1 : 16, g2 : 18, g3: 20, g4: 22, g5: 24,

    BT1: "디스크브레이크", BT2: "림브레이크",

    m1: "알루미늄", m2 :"카본",

    
  }
  ,
  data: [
    {
      productName: "test",
      manufacturer: "test",
      isFrame: false,
      productType: "test",
      numberGears: 25,
      breakType: "test",
      material: "test",
      weight: 26.6,
      productPrice: 1500000,
    },
    {
      productName: "test1",
      manufacturer: "test1",
      isFrame: false,
      productType: "test1",
      numberGears: 255,
      breakType: "test1",
      material: "test1",
      weight: 26.65,
      productPrice: 1500000,
    },
    {
      productName:
        "스페셜리시마 디스크 슈퍼레코드 EPS 12단 + NG Road 바이크어헤드 바이터보 로드 cl.",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "6.946",
      productPrice: "24000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633996139",
      productImg:
        "./img/Daejin/스페셜리시마 디스크 슈퍼레코드 EPS 12단 + NG Road 바이크어헤드 바이터보 로드 cl..jpg",
    },
    {
      productName: "스페셜리시마 디스크 슈퍼레코드 EPS 12단 울트라 WTO 45",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "6.746",
      productPrice: "20500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633997612",
      productImg:
        "./img/Daejin/스페셜리시마 디스크 슈퍼레코드 EPS 12단 울트라 WTO 45.jpg",
    },
    {
      productName: "스페셜리시마 디스크 슈퍼레코드 12단 울트라 WTO 45",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "6.715",
      productPrice: "18500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633998184",
      productImg:
        "./img/Daejin/스페셜리시마 디스크 슈퍼레코드 12단 울트라 WTO 45.jpg",
    },
    {
      productName: "스페셜리시마 슈퍼레코드 12단 보라 WTO 45",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "6.4",
      productPrice: "15600000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1584935652",
      productImg: "./img/Daejin/스페셜리시마 슈퍼레코드 12단 보라 WTO 45.jpg",
    },
    {
      productName: "스페셜리시마 타볼로짜 디스크 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.75",
      productPrice: "9000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1610346705",
      productImg: "./img/Daejin/스페셜리시마 타볼로짜 디스크 프레임.jpg",
    },
    {
      productName: "스페셜리시마 타볼로짜 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6800000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1609918168",
      productImg: "./img/Daejin/스페셜리시마 타볼로짜 프레임.jpg",
    },
    {
      productName: "스페셜리시마 CV 디스크 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.75",
      productPrice: "8950000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1612934258",
      productImg: "./img/Daejin/스페셜리시마 CV 디스크 프레임.jpg",
    },
    {
      productName: "스페셜리시마 CV 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6300000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1589507121",
      productImg: "./img/Daejin/스페셜리시마 CV 프레임.jpg",
    },
    {
      productName:
        "올트레 XR4 디스크 슈퍼레코드 EPS 12단 + NG Road 바이크어헤드 바이터보 에어로",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "6.7",
      productPrice: "22000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633677034",
      productImg:
        "./img/Daejin/올트레 XR4 디스크 슈퍼레코드 EPS 12단 + NG Road 바이크어헤드 바이터보 에어로.jpg",
    },
    {
      productName: "올트레 XR4 디스크 슈퍼레코드 EPS 12단 울트라 WTO 60",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "6.84",
      productPrice: "19500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633679318",
      productImg:
        "./img/Daejin/올트레 XR4 디스크 슈퍼레코드 EPS 12단 울트라 WTO 60.jpg",
    },
    {
      productName: "올트레 XR4 디스크 슈퍼레코드 12단 울트라 WTO 60",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "6.82",
      productPrice: "17000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633680055",
      productImg:
        "./img/Daejin/올트레 XR4 디스크 슈퍼레코드 12단 울트라 WTO 60.jpg",
    },
    {
      productName: "올트레 XR4 디스크 슈퍼레코드 EPS 12단 + NG Eco 보라 WTO 45",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7",
      productPrice: "18600000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585014615",
      productImg:
        "./img/Daejin/올트레 XR4 디스크 슈퍼레코드 EPS 12단 + NG Eco 보라 WTO 45.jpg",
    },
    {
      productName: "올트레 XR4 슈퍼레코드 EPS 12단 보라 WTO 45",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "6.63",
      productPrice: "16500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1584938771",
      productImg: "./img/Daejin/올트레 XR4 슈퍼레코드 EPS 12단 보라 WTO 45.jpg",
    },
    {
      productName: "올트레 XR4 슈퍼레코드 12단 보라 WTO 45",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "6.6",
      productPrice: "14300000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1584935955",
      productImg: "./img/Daejin/올트레 XR4 슈퍼레코드 12단 보라 WTO 45.jpg",
    },
    {
      productName: "올트레 XR4 코러스 12단 보라 WTO 60",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "6.98",
      productPrice: "11300000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1584941672",
      productImg: "./img/Daejin/올트레 XR4 코러스 12단 보라 WTO 60.jpg",
    },
    {
      productName: "올트레 XR4 디스크 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.99",
      productPrice: "7500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633571804",
      productImg: "./img/Daejin/올트레 XR4 디스크 프레임.jpg",
    },
    {
      productName: "올트레 XR4 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.98",
      productPrice: "5700000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633572988",
      productImg: "./img/Daejin/올트레 XR4 프레임.jpg",
    },
    {
      productName: "올트레 XR4 타볼로짜 디스크 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.99",
      productPrice: "8000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1610341933",
      productImg: "./img/Daejin/올트레 XR4 타볼로짜 디스크 프레임.jpg",
    },
    {
      productName: "올트레 XR4 타볼로짜 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.98",
      productPrice: "6200000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1609828970",
      productImg: "./img/Daejin/올트레 XR4 타볼로짜 프레임.jpg",
    },
    {
      productName: "올트레 XR3 울테그라 11단 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "8.5",
      productPrice: "8500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585006182",
      productImg: "./img/Daejin/올트레 XR3 울테그라 11단 디스크.jpg",
    },
    {
      productName: "아리아 Rival 12단 WTO 60 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "8.802",
      productPrice: "8900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1650862356",
      productImg: "./img/Daejin/아리아 Rival 12단 WTO 60 디스크.jpg",
    },
    {
      productName: "아리아 코러스 12단 샤말 카본 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "8.08",
      productPrice: "7950000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1638341093",
      productImg: "./img/Daejin/아리아 코러스 12단 샤말 카본 디스크.jpg",
    },
    {
      productName: "아리아 코러스 12단 시로코 2WF DB cl.",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "8.234",
      productPrice: "6700000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1661323565",
      productImg: "./img/Daejin/아리아 코러스 12단 시로코 2WF DB cl..jpg",
    },
    {
      productName: "아리아 울테그라 11단 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "6500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585038236",
      productImg: "./img/Daejin/아리아 울테그라 11단 디스크.jpg",
    },
    {
      productName: "아리아 디스크 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "1.15",
      productPrice: "4200000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1653529790",
      productImg: "./img/Daejin/아리아 디스크 프레임.jpg",
    },
    {
      productName: "스프린트 센타우르 11단 칼리마 cl.",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "8.69",
      productPrice: "3950000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1652157802",
      productImg: "./img/Daejin/스프린트 센타우르 11단 칼리마 cl..jpg",
    },
    {
      productName: "스프린트 105 11단 칼리마 cl.",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "8.69",
      productPrice: "3750000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1656655496",
      productImg: "./img/Daejin/스프린트 105 11단 칼리마 cl..jpg",
    },
    {
      productName: "인피니토 CV 코러스 12단 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "9900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1616985628",
      productImg: "./img/Daejin/인피니토 CV 코러스 12단 디스크.jpg",
    },
    {
      productName: "인피니토 CV 디스크 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "5900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585017163",
      productImg: "./img/Daejin/인피니토 CV 디스크 프레임.jpg",
    },
    {
      productName: "인피니토 XE 울테그라 11단 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "8.5",
      productPrice: "4700000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585022498",
      productImg: "./img/Daejin/인피니토 XE 울테그라 11단 디스크.jpg",
    },
    {
      productName: "니로네 7 105 11단 디스크",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "알루미늄",
      weight: "9.45",
      productPrice: "2790000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633583963",
      productImg: "./img/Daejin/니로네 7 105 11단 디스크.jpg",
    },
    {
      productName: "니로네 7 105 11단",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "알루미늄",
      weight: "9.25",
      productPrice: "1990000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585025787",
      productImg: "./img/Daejin/니로네 7 105 11단.jpg",
    },
    {
      productName: "니로네 7 클라리스 8단",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "로드",
      numberGears: "16",
      breakType: "림브레이크",
      material: "알루미늄",
      weight: "10.12",
      productPrice: "1190000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1589337666",
      productImg: "./img/Daejin/니로네 7 클라리스 8단.jpg",
    },
    {
      productName: "아퀼라 CV 슈퍼레코드 EPS 12단",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "타임트라이얼",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "28000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585099647",
      productImg: "./img/Daejin/아퀼라 CV 슈퍼레코드 EPS 12단.jpg",
    },
    {
      productName: "아퀼라 CV 프레임",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "타임트라이얼",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "1.45",
      productPrice: "11500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585051801",
      productImg: "./img/Daejin/아퀼라 CV 프레임.jpg",
    },
    {
      productName: "졸더 프로 디스크 코러스 12단",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "사이클로크로스",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "7800000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1586301896",
      productImg: "./img/Daejin/졸더 프로 디스크 코러스 12단.jpg",
    },
    {
      productName: "졸더 프로 프레임 - 디스크",
      manufacturer: "비앙키",
      isFrame: true,
      productType: "사이클로크로스",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.99",
      productPrice: "3500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1586301448",
      productImg: "./img/Daejin/졸더 프로 프레임 - 디스크.jpg",
    },
    {
      productName: "임풀소 올-로드",
      manufacturer: "비앙키",
      isFrame: false,
      productType: "그래블",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "알루미늄",
      weight: "10.11",
      productPrice: "3590000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1633585853",
      productImg: "./img/Daejin/임풀소 올-로드.jpg",
    },
    {
      productName:
        "RANGER Disc Team Limited 슈퍼레코드 12단 EPS + 보라 울트라 WTO 45",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "12900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645681022",
      productImg:
        "./img/Daejin/RANGER Disc Team Limited 슈퍼레코드 12단 EPS + 보라 울트라 WTO 45.jpg",
    },
    {
      productName: "RANGER Disc Legend 코러스 12단 디스크 + 샤말 카본 DB",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "5900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645686270",
      productImg:
        "./img/Daejin/RANGER Disc Legend 코러스 12단 디스크 + 샤말 카본 DB.jpg",
    },
    {
      productName: "RANGER Disc Team Limited 울테그라 11단 + 어택 45 카본 DB",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "3590000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645686995",
      productImg:
        "./img/Daejin/RANGER Disc Team Limited 울테그라 11단 + 어택 45 카본 DB.jpg",
    },
    {
      productName: "RANGER Disc Pro Ultra 울테그라 11단 + 어택 45 카본 DB",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "3590000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645687560",
      productImg:
        "./img/Daejin/RANGER Disc Pro Ultra 울테그라 11단 + 어택 45 카본 DB.jpg",
    },
    {
      productName: "RANGER Disc Sport 105 11단 + 펄크럼 레이싱 900 DB",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "2890000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645688026",
      productImg:
        "./img/Daejin/RANGER Disc Sport 105 11단 + 펄크럼 레이싱 900 DB.jpg",
    },
    {
      productName: "RANGER Team Limited 레코드 12단 + 보라 WTO 45",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "7300000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645688926",
      productImg:
        "./img/Daejin/RANGER Team Limited 레코드 12단 + 보라 WTO 45.jpg",
    },
    {
      productName: "RANGER Team Limited 울테그라 11단 + 어택 45 카본",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "3190000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645689660",
      productImg:
        "./img/Daejin/RANGER Team Limited 울테그라 11단 + 어택 45 카본.jpg",
    },
    {
      productName: "RANGER Pro Ultra 울테그라 11단 + 어택 45 카본",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "3190000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645690289",
      productImg:
        "./img/Daejin/RANGER Pro Ultra 울테그라 11단 + 어택 45 카본.jpg",
    },
    {
      productName: "RANGER Sport 105 11단 + 칼리마 cl.",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "2090000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1646354847",
      productImg: "./img/Daejin/RANGER Sport 105 11단 + 칼리마 cl..jpg",
    },
    {
      productName: "COBRA Sport 105 11단 + 어택 알루 휠",
      manufacturer: "구스토",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "1890000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1645691077",
      productImg: "./img/Daejin/COBRA Sport 105 11단 + 어택 알루 휠.jpg",
    },
    {
      productName:
        "알프 듀에즈 01 액티브 디스크 리미티드 에디션 슈퍼레코드 EPS 12단 + NG Eco 파워미터",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.44",
      productPrice: "19700000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585550458",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 디스크 리미티드 에디션 슈퍼레코드 EPS 12단 + NG Eco 파워미터",
    },
    {
      productName:
        "알프 듀에즈 01 액티브 디스크 리미티드 에디션 슈퍼레코드 EPS 12단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.422",
      productPrice: "18400000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1583282678",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 디스크 리미티드 에디션 슈퍼레코드 EPS 12단",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 슈퍼레코드 EPS 12단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.45",
      productPrice: "17900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585555165",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 디스크 슈퍼레코드 EPS 12단",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 슈퍼레코드 12단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.429",
      productPrice: "15400000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585555424",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 디스크 슈퍼레코드 12단",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 eTap AXS 12",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.605",
      productPrice: "14500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585554835",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 디스크 eTap AXS 12",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 DURA ACE 12단 + 샤말 카본 DB",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.5",
      productPrice: "14900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1651475537",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 디스크 DURA ACE 12단 + 샤말 카본 DB",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 레코드 12단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.594",
      productPrice: "12900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585555683",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 디스크 레코드 12단",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 리미티드 에디션 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "8500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585551001",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 디스크 리미티드 에디션 프레임",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "8000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585612755",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 디스크 프레임",
    },
    {
      productName: "알프 듀에즈 01 액티브 디스크 레이싱 팩토리 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "8000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1594278338",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 디스크 레이싱 팩토리 프레임",
    },
    {
      productName:
        "알프 듀에즈 01 액티브 슈퍼레코드 EPS 12단 + Power2Max NG Eco",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "7.24",
      productPrice: "17500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585558446",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 슈퍼레코드 EPS 12단 + Power2Max NG Eco",
    },
    {
      productName: "알프 듀에즈 01 액티브 슈퍼레코드 12단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "7.229",
      productPrice: "15400000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585558010",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 슈퍼레코드 12단",
    },
    {
      productName: "알프 듀에즈 01 액티브 리미티드 에디션 레코드 12단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "림브레이크",
      material: "카본",
      weight: "7.394",
      productPrice: "9900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1617866761",
      productImg:
        "./img/Daejin/알프 듀에즈 01 액티브 리미티드 에디션 레코드 12단",
    },
    {
      productName: "알프 듀에즈 01 액티브 리미티드 에디션",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "7000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585612282",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 리미티드 에디션",
    },
    {
      productName: "알프 듀에즈 01 액티브 레이싱 팩토리",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "6500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585554438",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 레이싱 팩토리",
    },
    {
      productName: "알프 듀에즈 01 액티브 레드 + 그레이",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "6500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1595836132",
      productImg: "./img/Daejin/알프 듀에즈 01 액티브 레드 + 그레이",
    },
    {
      productName: "알프 듀에즈 01.1 액티브 블랙",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "0.84",
      productPrice: "6500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585553045",
      productImg: "./img/Daejin/알프 듀에즈 01.1 액티브 블랙",
    },
    {
      productName: "알프듀에즈 21 슈퍼레코드 12단 EPS 울트라 WTO 45 DB",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.222",
      productPrice: "15000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1665558804",
      productImg:
        "./img/Daejin/알프듀에즈 21 슈퍼레코드 12단 EPS 울트라 WTO 45 DB",
    },
    {
      productName: "알프듀에즈 21 슈퍼레코드 EPS 12단 샤말 카본 DB",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.61",
      productPrice: "12500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1658890471",
      productImg: "./img/Daejin/알프듀에즈 21 슈퍼레코드 EPS 12단 샤말 카본 DB",
    },
    {
      productName: "알프듀에즈 21 코러스 12단 샤말 카본 DB",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "7.9",
      productPrice: "9700000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1657697738",
      productImg: "./img/Daejin/알프듀에즈 21 코러스 12단 샤말 카본 DB",
    },
    {
      productName: "알프듀에즈 21 Rival 12단 시로코 2WF DB",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "8.47",
      productPrice: "8500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1657693689",
      productImg: "./img/Daejin/알프듀에즈 21 Rival 12단 시로코 2WF DB",
    },
    {
      productName: "알프듀에즈 21 디스크 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.93",
      productPrice: "5500000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1654821138",
      productImg: "./img/Daejin/알프듀에즈 21 디스크 프레임",
    },
    {
      productName: "알프 듀에즈 21.3 울테그라 11단",
      manufacturer: "타임",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "6100000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1585557046",
      productImg: "./img/Daejin/알프 듀에즈 21.3 울테그라 11단",
    },
    {
      productName: "스카이론 액티브 디스크 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "0.95",
      productPrice: "6900000",
      productURL: "http://www.daejinkr.com/shop/list.php?ca_id=c1011010",
      productImg: "./img/Daejin/스카이론 액티브 디스크 프레임",
    },
    {
      productName: "스카이론 액티브 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "림브레이크",
      material: "카본",
      weight: "",
      productPrice: "6900000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1642643666",
      productImg: "./img/Daejin/스카이론 액티브 프레임",
    },
    {
      productName: "ADHX 에카르 13단 레반테 DB",
      manufacturer: "타임",
      isFrame: false,
      productType: "그래블",
      numberGears: "13",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "",
      productPrice: "11990000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1667267697",
      productImg: "./img/Daejin/ADHX 에카르 13단 레반테 DB",
    },
    {
      productName: "ADHX 그래블 프레임",
      manufacturer: "타임",
      isFrame: true,
      productType: "그래블",
      numberGears: "",
      breakType: "디스크브레이크",
      material: "카본",
      weight: "1.025",
      productPrice: "6000000",
      productURL: "http://www.daejinkr.com/shop/item.php?it_id=1658471302",
      productImg: "./img/Daejin/ADHX 그래블 프레임",
    },
    {
      productName: "FACTOR OSTRO VAM 캐나다 챔프 에디션",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14179",
      productImg: "./img/GLCO/FACTOR OSTRO VAM 캐나다 챔프 에디션.jpg",
    },
    {
      productName: "FACTOR OSTRO VAM 2022 TDF 에디션",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14082",
      productImg: "./img/GLCO/FACTOR OSTRO VAM 2022 TDF 에디션.jpg",
    },
    {
      productName: "FACTOR OSTRO VAM PHOENIX RISING 에디션",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14245",
      productImg: "./img/GLCO/FACTOR OSTRO VAM PHOENIX RISING 에디션.jpg",
    },
    {
      productName: "FACTOR OSTRO VAM OCEANIC 에디션",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14256",
      productImg: "./img/GLCO/FACTOR OSTRO VAM OCEANIC 에디션.jpg",
    },
    {
      productName: "FACTOR OSTRO VAM (레이싱 그린)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14015",
      productImg: "./img/GLCO/FACTOR OSTRO VAM (레이싱 그린).jpg",
    },
    {
      productName: "FACTOR OSTRO VAM (크롬)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13684",
      productImg: "./img/GLCO/FACTOR OSTRO VAM (크롬).jpg",
    },
    {
      productName: "FACTOR OSTRO VAM (플리커)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13683",
      productImg: "./img/GLCO/FACTOR OSTRO VAM (플리커).jpg",
    },
    {
      productName: "FACTOR OSTRO VAM (소호 믹스)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.78",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13686",
      productImg: "./img/GLCO/FACTOR OSTRO VAM (소호 믹스).jpg",
    },
    {
      productName: "FACTOR O2 VAM (네이키드블랙/크롬)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.677",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14030",
      productImg: "./img/GLCO/FACTOR O2 VAM (네이키드블랙/크롬).jpg",
    },
    {
      productName: "FACTOR O2 VAM (Ornate Azure)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.677",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14029",
      productImg: "./img/GLCO/FACTOR O2 VAM (Ornate Azure).jpg",
    },
    {
      productName: "FACTOR O2 VAM (Ornate Nero)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.677",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14028",
      productImg: "./img/GLCO/FACTOR O2 VAM (Ornate Nero).jpg",
    },
    {
      productName: "FACTOR O2 (와일드 마이애미 페이드)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.87",
      productPrice: "3400000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13253",
      productImg: "./img/GLCO/FACTOR O2 (와일드 마이애미 페이드).jpg",
    },
    {
      productName: "FACTOR O2 (마일드 펄화이트)",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.87",
      productPrice: "3400000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13252",
      productImg: "./img/GLCO/FACTOR O2 (마일드 펄화이트).jpg",
    },
    {
      productName: "FACTOR OSTRO GRAVEL",
      manufacturer: "팩터",
      isFrame: true,
      productType: "그래블",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "0.9",
      productPrice: "6900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14260",
      productImg: "./img/GLCO/FACTOR OSTRO GRAVEL.jpg",
    },
    {
      productName: "FACTOR LS",
      manufacturer: "팩터",
      isFrame: true,
      productType: "그래블",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "1.013",
      productPrice: "3400000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13761",
      productImg: "./img/GLCO/FACTOR LS.jpg",
    },
    {
      productName: "FACTOR HANZŌ",
      manufacturer: "팩터",
      isFrame: true,
      productType: "타임트라이얼",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "",
      productPrice: "7900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14063",
      productImg: "./img/GLCO/FACTOR HANZŌ.jpg",
    },
    {
      productName: "FACTOR SLICK",
      manufacturer: "팩터",
      isFrame: true,
      productType: "타임트라이얼",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "",
      productPrice: "7900000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13755",
      productImg: "./img/GLCO/FACTOR SLICK.jpg",
    },
    {
      productName: "FACTOR ONE",
      manufacturer: "팩터",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "1.12",
      productPrice: "6600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13762",
      productImg: "./img/GLCO/FACTOR ONE.jpg",
    },
    {
      productName: "메티 D1 (클라리스 디스크)",
      manufacturer: "예거",
      isFrame: false,
      productType: "로드",
      numberGears: "16",
      breakType: "디스크 브레이크",
      material: "알루미늄",
      weight: "11.2",
      productPrice: "720000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14250",
      productImg: "./img/GLCO/메티 D1(클라리스 디스크).jpg",
    },
    {
      productName: "메티 D3 (소라 디스크)",
      manufacturer: "예거",
      isFrame: false,
      productType: "로드",
      numberGears: "18",
      breakType: "디스크 브레이크",
      material: "알루미늄",
      weight: "11.1",
      productPrice: "820000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14251",
      productImg: "./img/GLCO/메티 D3 (소라 디스크).jpg",
    },
    {
      productName: "마리온 RX (RIVAL eTAP AXS)",
      manufacturer: "예거",
      isFrame: false,
      productType: "로드",
      numberGears: "24",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "8.7",
      productPrice: "3990000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=14447",
      productImg: "./img/GLCO/마리온 RX (RIVAL eTAP AXS).jpg",
    },
    {
      productName: "WILIER 0 SL (완성차)",
      manufacturer: "윌리어",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "8.35",
      productPrice: "5300000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13411",
      productImg: "./img/GLCO/WILIER 0 SL (완성차).jpg",
    },
    {
      productName: "CENTO 10 SL(완성차)",
      manufacturer: "윌리어",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "8.35",
      productPrice: "4600000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13408",
      productImg: "./img/GLCO/CENTO 10 SL(완성차).jpg",
    },
    {
      productName: "WILIER 0 SLR (프레임 세트)",
      manufacturer: "윌리어",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "1.12",
      productPrice: "5500000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13412",
      productImg: "./img/GLCO/WILIER 0 SLR (프레임 세트).jpg",
    },
    {
      productName: "FILANTE SLR (프레임세트)",
      manufacturer: "윌리어",
      isFrame: true,
      productType: "로드",
      numberGears: "",
      breakType: "디스크 브레이크",
      material: "카본",
      weight: "1.23",
      productPrice: "5500000",
      productURL:
        "https://www.glnco.co.kr/product/product_view.html?b_code=13409",
      productImg: "./img/GLCO/FILANTE SLR(프레임세트).jpg",
    },
    {
      productName: "FINISSIMO CLARIS",
      manufacturer: "인세인",
      isFrame: false,
      productType: "로드",
      numberGears: "16",
      breakType: "림 브레이크",
      material: "카본",
      weight: "9.21",
      productPrice: "930000",
      productURL: "https://insainnebike.com/shop/item.php?it_id=1649490073",
      productImg:
        "https://insainnebike.com/data/item/1649490073/FINISSIMOCLARIS_Black_Red_1.jpg",
    },
    {
      productName: "FINISSIMO 105",
      manufacturer: "인세인",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림 브레이크",
      material: "카본",
      weight: "8.5",
      productPrice: "1290000",
      productURL: "https://insainnebike.com/shop/item.php?it_id=1551250451",
      productImg:
        "https://insainnebike.com/data/item/1551250451/finissimo_105.jpg",
    },
    {
      productName: "FINISSIMO ULTE",
      manufacturer: "인세인",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림 브레이크",
      material: "카본",
      weight: "8.3",
      productPrice: "1690000",
      productURL: "https://insainnebike.com/shop/item.php?it_id=1551250461",
      productImg:
        "https://insainnebike.com/data/item/1551250461/finissimo_ulte_bk.jpg",
    },
    {
      productName: "QUUVE ULTE",
      manufacturer: "인세인",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림 브레이크",
      material: "카본",
      weight: "7.43",
      productPrice: "3200000",
      productURL: "https://insainnebike.com/shop/item.php?it_id=1554187262",
      productImg:
        "https://insainnebike.com/data/item/1554187262/QUUVE_ulte_bk.jpg",
    },
    {
      productName: "QUUVE DURA",
      manufacturer: "인세인",
      isFrame: false,
      productType: "로드",
      numberGears: "22",
      breakType: "림 브레이크",
      material: "카본",
      weight: "7.11",
      productPrice: "6500000",
      productURL: "https://insainnebike.com/shop/item.php?it_id=1554189006",
      productImg:
        "https://insainnebike.com/data/item/1554189006/QUUVE_ulte_bk.jpg",
    },
  ],
};

export default data;
